<?php

namespace OGame\Ogx3d\Services;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\File;
use OGame\Ogx3d\Models\Ogx3dOverride;
use Throwable;

/**
 * Turns the admin's assignments into the two things the browser needs:
 *
 *   css()       one !important background rule per selector, for the flat icons
 *   manifest()  a small json blob naming which objects and which slots have a model
 *
 * Both are built per version and cached, and both are EMPTY under V1 - not "mostly
 * empty", empty. That is what makes V1 provably the untouched game: there is no code
 * path that emits a byte for it.
 */
class Ogx3dAssets
{
    /** Where admin uploads are written to, under public/. */
    public const string UPLOAD_DIR = 'ogx3d/uploads';

    /**
     * The upload folder for one version.
     *
     * The version segment is not decoration. Naming an upload after the object alone
     * means the moment two versions override the same object, the second upload
     * overwrites the first version's artwork on disk while both database rows still
     * point at that one path - so changing V3 silently changes V2, which is precisely
     * the independence the versions exist to provide.
     */
    public function uploadDir(string $version): string
    {
        return self::UPLOAD_DIR . '/' . $version;
    }

    public function __construct(
        private readonly Ogx3dVersions $versions,
        private readonly Ogx3dRegistry $registry,
    ) {
    }

    /* =====================================================================
     * Reading the assignments
     * ================================================================== */

    /**
     * Every assignment in one version, keyed by target.
     *
     * @return array<string, Ogx3dOverride>
     */
    public function overrides(string $version): array
    {
        if ($version === Ogx3dVersions::ORIGINAL || !$this->versions->ready()) {
            return [];
        }

        try {
            /** @var array<string, Ogx3dOverride> $rows */
            $rows = Ogx3dOverride::where('version_key', $version)->get()->keyBy('target')->all();

            return $rows;
        } catch (Throwable) {
            return [];
        }
    }

    public function override(string $version, string $target): Ogx3dOverride|null
    {
        return $this->overrides($version)[$target] ?? null;
    }

    /* =====================================================================
     * The generated stylesheet
     * ================================================================== */

    /**
     * A short hash of the generated files, used as the ?v= on the <link> and <script>.
     *
     * Hashing the BODY rather than the rows' timestamps is deliberate: with timestamps
     * only, a change to the generator itself leaves every browser on a stale copy until
     * max-age expires, and "I changed the code and nothing happened" is the least
     * debuggable bug there is.
     */
    public function stamp(string $version): string
    {
        return substr(md5($this->css($version) . '|' . $this->manifestJson($version)), 0, 10);
    }

    public function css(string $version): string
    {
        if ($version === Ogx3dVersions::ORIGINAL) {
            return '';
        }

        $key = 'ogx3d.css.' . $version;
        $cached = Cache::get($key);
        if (is_string($cached)) {
            return $cached;
        }

        $css = $this->buildCss($version);
        Cache::forever($key, $css);

        return $css;
    }

    private function buildCss(string $version): string
    {
        $out = [
            '/* GENERATED by the OgameX 3D Mod for graphics version ' . strtoupper($version) . '.',
            '   One rule per css selector that paints an overridden object, so a single',
            '   uploaded image replaces that object on every screen at once.',
            '   Do not edit: this file is rebuilt whenever an assignment changes. */',
            '',
            '/* Anything hosting a live 3D view drops its own background, or the flat',
            '   artwork would sit on top of the canvas. */',
            '.ogx3d-live { background-image: none !important; background: none !important; }',
            '.ogx3d-mount { position: absolute; inset: 0; z-index: 0; cursor: grab; }',
            '.ogx3d-mount canvas { display: block; width: 100%; height: 100%; }',
            '/* #planet carries z-index:1 in the stock theme while the detail popup that',
            '   overlays it has none. A static background loses that race harmlessly; a',
            '   canvas that repaints every frame does not, and shows through the popup. */',
            '#technologydetails_wrapper { z-index: 2; }',
        ];

        foreach ($this->overrides($version) as $target => $override) {
            $image = (string) ($override->image_path ?? '');
            if ($image === '') {
                continue;
            }
            $selectors = $this->registry->selectors($target);
            if ($selectors === []) {
                continue;
            }

            $url = $this->cssUrl($image);
            $entry = $this->registry->get($target);

            $out[] = '';
            $out[] = '/* ' . $target . ' - ' . (string) ($entry['title'] ?? '') . ' (' . count($selectors) . ' selectors) */';

            foreach ($selectors as $selector) {
                /*
                 * ONE RULE PER SELECTOR, NOT ONE RULE PER OBJECT.
                 *
                 * Css selector lists are all-or-nothing: if a browser cannot parse ONE
                 * selector in a comma group it throws away the WHOLE rule, silently and
                 * without a console message. Grouping an object's eight selectors would
                 * mean one odd entry in the registry - a stray character out of the
                 * game's own stylesheet - takes that object's other seven screens down
                 * with it, and the symptom is "the upload did nothing".
                 *
                 * Separate rules cost a few hundred bytes in a gzipped, cached file and
                 * buy the property that a bad selector can only break itself.
                 */
                $out[] = $selector . ' {';
                $out[] = "    background-image: url('" . $url . "') !important;";
                $out[] = '    background-position: center center !important;';
                $out[] = '    background-size: contain !important;';
                $out[] = '    background-repeat: no-repeat !important;';
                $out[] = '}';

                // The atlases encode "disabled" and "unavailabe" (the game's own
                // spelling - not a typo to fix here, correcting it would simply stop
                // matching) as further ROWS of the same sheet, picked with
                // background-position-y. A single replacement image has no rows, so
                // those states would render identically to the normal one. Express them
                // as a filter instead, scoped to this object's own selectors - a blanket
                // .disabled rule would grey out icons nobody overrode.
                if (str_contains($selector, '.sprite') && !str_contains($selector, '::')) {
                    $out[] = $selector . '.disabled, ' . $selector . '.unavailabe {';
                    $out[] = '    filter: grayscale(1) brightness(0.55) !important;';
                    $out[] = '}';
                }
            }
        }

        return implode("\n", $out) . "\n";
    }

    /* =====================================================================
     * The manifest the browser reads
     * ================================================================== */

    public function manifestJson(string $version): string
    {
        if ($version === Ogx3dVersions::ORIGINAL) {
            return '{"version":"v1","objects":{},"slots":{}}';
        }

        $key = 'ogx3d.manifest.' . $version;
        $cached = Cache::get($key);
        if (is_string($cached)) {
            return $cached;
        }

        $json = (string) json_encode($this->manifest($version), JSON_UNESCAPED_SLASHES);
        Cache::forever($key, $json);

        return $json;
    }

    /**
     * @return array<string, mixed>
     */
    public function manifest(string $version): array
    {
        /** @var array<string, array<string, mixed>> $slotConfig */
        $slotConfig = config('ogx3d.slots', []);
        /** @var array<string, mixed> $defaults */
        $defaults = config('ogx3d.defaults', []);

        $objects = [];
        $slots = [];

        foreach ($this->overrides($version) as $target => $override) {
            $model = (string) ($override->model_path ?? '');
            if ($model === '' || !is_file(public_path($model))) {
                continue;
            }

            $isSlot = array_key_exists($target, $slotConfig);
            /** @var array<string, mixed> $slot */
            $slot = $isSlot ? $slotConfig[$target] : [];

            $entry = [
                'model' => $this->modelUrl($model),
                'preset' => (string) ($override->model_preset ?? $defaults['preset'] ?? 'studio'),
                'motion' => (string) ($override->model_motion ?? $slot['motion'] ?? $defaults['motion'] ?? 'hover'),
                'spin' => (float) ($override->model_spin ?? $defaults['spin'] ?? 1.0),
                'zoom' => (float) ($override->model_zoom ?? $defaults['zoom'] ?? 1.0),
                'view' => (string) ($slot['view'] ?? 'icon'),
                'shadow' => (float) ($defaults['shadow'] ?? 0.36),
            ];

            if ($isSlot) {
                $entry['find'] = (string) ($slot['find'] ?? '');
                $entry['unless'] = (string) ($slot['unless'] ?? '');
                $entry['only_with'] = (string) ($slot['only_with'] ?? '');
                // Wide banner strips keep their panorama and fly the model in front of
                // it, which is what makes the screen still read as the game. A game
                // object's artwork box does not: its icon would sit on top of the canvas.
                $entry['keep_bg'] = (bool) ($slot['keep_background'] ?? false);
                $slots[$target] = $entry;
            } else {
                $objects[$target] = $entry;
            }
        }

        return [
            'version' => $version,
            'presets' => $this->presetsForBrowser(),
            'objects' => $objects,
            'slots' => $slots,
            'images' => $this->imageMap($version),
        ];
    }

    /**
     * Original image path => replacement url, for the icons that are real <img> tags.
     *
     * WHY THIS IS NEEDED AT ALL
     * -------------------------
     * The generated stylesheet reaches every icon that is painted as a css background,
     * which is most of them. It cannot reach the ones the game emits as <img src=...>:
     * the build queues and the battle report do that, using
     * GameObjectAssets::$imgSmall / $imgMicro under img/objects/.
     *
     * So an object swapped in the admin screen used to show its NEW artwork in the
     * shipyard and its OLD artwork while it was being built - which reads as the mod
     * being unreliable rather than as two different mechanisms. This map lets the
     * browser side finish the job, without a single template being edited.
     *
     * The map is built from the game's own asset fields rather than from a guessed
     * filename pattern, so it stays right if an object's artwork is renamed.
     *
     * @return array<string, string>
     */
    private function imageMap(string $version): array
    {
        $overrides = $this->overrides($version);
        if ($overrides === []) {
            return [];
        }

        try {
            $objects = \OGame\Services\ObjectService::getObjects();
        } catch (Throwable) {
            // A game that cannot list its own objects has larger problems than this
            // map; the css overrides still work without it.
            return [];
        }

        $map = [];
        foreach ($objects as $object) {
            $override = $overrides[$object->class_name] ?? null;
            $image = (string) ($override?->image_path ?? '');
            if ($image === '') {
                continue;
            }

            $folder = match ($object->type) {
                \OGame\GameObjects\Models\Enums\GameObjectType::Building,
                \OGame\GameObjects\Models\Enums\GameObjectType::Station => 'img/objects/buildings/',
                \OGame\GameObjects\Models\Enums\GameObjectType::Research => 'img/objects/research/',
                default => 'img/objects/units/',
            };

            $replacement = asset($image);
            // Per object, not around the whole loop. GameObjectAssets declares its two
            // fields as typed strings with no default, so an object somebody added
            // without filling them in throws on read - and catching that outside the
            // loop would let ONE such object silently empty the map for every object,
            // which looks like "the mod stopped working" rather than "that one object
            // has no artwork listed".
            try {
                foreach ([$object->assets->imgSmall, $object->assets->imgMicro] as $file) {
                    if ($file !== '') {
                        $map[$folder . $file] = $replacement;
                    }
                }
            } catch (Throwable) {
                continue;
            }
        }

        return $map;
    }

    /**
     * The lighting presets, flattened into what the viewer actually reads.
     *
     * Kept in the manifest rather than duplicated in the js file so that adding a
     * preset is a config change and nothing else - the previous arrangement kept the
     * numbers in the js and a pick-list in php, and the two drifted apart.
     *
     * @return array<string, mixed>
     */
    private function presetsForBrowser(): array
    {
        /** @var array<string, array<string, mixed>> $presets */
        $presets = config('ogx3d.presets', []);
        $out = [];
        foreach ($presets as $key => $preset) {
            $out[$key] = [
                'sky' => $preset['sky'] ?? '#2a3644',
                'haze' => $preset['haze'] ?? '#161e28',
                'sun' => $preset['sun'] ?? ['f' => '#ffffff', 'i' => 4.4, 'p' => [4, 6, 7]],
                'rim' => $preset['rim'] ?? ['f' => '#7fa8d8', 'i' => 1.4, 'p' => [-6, -2, -5]],
                'amb' => $preset['amb'] ?? ['top' => '#8fabc8', 'bottom' => '#222c38', 'i' => 1.6],
            ];
        }

        return $out;
    }

    /**
     * One image path, safe to drop inside url('...') in generated css.
     *
     * The path is built from an admin's own filename, and a stylesheet is code: a
     * single quote in it would close the url and let the rest of the name be parsed as
     * further css. Everything that could end a string, a declaration or a rule is
     * percent-encoded, which a browser resolves back to the same file.
     */
    private function cssUrl(string $image): string
    {
        $path = '/' . ltrim($image, '/');

        // An allow-list, not a list of villains: a path segment is letters, digits and
        // the handful of punctuation marks a filename normally uses. Everything else -
        // quotes, brackets, semicolons, braces, control characters, anything above
        // ascii - is percent-encoded, which a browser resolves back to the same file
        // and a css parser cannot read as anything but text.
        return (string) preg_replace_callback(
            '/[^A-Za-z0-9\/._~-]/',
            static fn (array $m): string => rawurlencode($m[0]),
            $path
        );
    }

    /**
     * A model's url with a cache-busting stamp keyed on the file's own timestamp.
     *
     * Without it a browser holds a .glb forever, and replacing the file in the drop
     * folder appears to do nothing at all - which reads as "the mod is broken" rather
     * than "your browser kept the old one".
     */
    public function modelUrl(string $path): string
    {
        $abs = public_path($path);

        return asset($path) . (is_file($abs) ? '?v=' . filemtime($abs) : '');
    }

    /* =====================================================================
     * The drop folders
     * ================================================================== */

    /**
     * Every model file the admin has put in the drop folder, relative to public/.
     *
     * @return array<int, string>
     */
    public function availableModels(): array
    {
        return $this->filesIn((string) config('ogx3d.model_dir'), ['glb', 'gltf']);
    }

    /**
     * Every icon the admin has put in the drop folder, relative to public/.
     *
     * @return array<int, string>
     */
    public function availableIcons(): array
    {
        return $this->filesIn((string) config('ogx3d.icon_dir'), ['png', 'jpg', 'jpeg', 'gif', 'webp']);
    }

    /**
     * @param array<int, string> $extensions
     *
     * @return array<int, string>
     */
    private function filesIn(string $dir, array $extensions): array
    {
        if ($dir === '') {
            return [];
        }
        $abs = public_path($dir);
        // Recreate a drop folder somebody deleted: an empty folder that exists is a
        // hint about what to do, a missing one is a bug report.
        if (!File::isDirectory($abs)) {
            try {
                File::ensureDirectoryExists($abs);
            } catch (Throwable) {
                return [];
            }
        }

        $found = [];
        foreach (File::allFiles($abs) as $file) {
            if (!in_array(strtolower($file->getExtension()), $extensions, true)) {
                continue;
            }
            $found[] = $dir . '/' . str_replace('\\', '/', $file->getRelativePathname());
        }
        sort($found);

        return $found;
    }

    /* =====================================================================
     * Cache
     * ================================================================== */

    public function invalidate(string|null $version = null): void
    {
        if ($version !== null) {
            Cache::forget('ogx3d.css.' . $version);
            Cache::forget('ogx3d.manifest.' . $version);

            return;
        }
        foreach (array_keys($this->versions->all()) as $key) {
            Cache::forget('ogx3d.css.' . $key);
            Cache::forget('ogx3d.manifest.' . $key);
        }
    }

    /* =====================================================================
     * three.js
     * ================================================================== */

    /**
     * The import map for three.js.
     *
     * A local copy under public/ogx3d/vendor/three wins automatically, so an admin who
     * does not want a cdn only has to put the files there - no config change, nothing
     * to remember. The trailing slash on the addons value is MANDATORY: a prefix
     * mapping whose value does not end in "/" is silently mapped to null by the
     * browser, taking every addon import down with it.
     *
     * @return array<string, string>
     */
    public function threeImports(): array
    {
        $local = 'ogx3d/vendor/three/three.module.js';
        if (is_file(public_path($local))) {
            return [
                'three' => asset($local),
                'three/addons/' => asset('ogx3d/vendor/three/examples/jsm') . '/',
            ];
        }

        $cdn = rtrim((string) config('ogx3d.three_cdn'), '/') . '/';

        return [
            'three' => $cdn . 'build/three.module.js',
            'three/addons/' => $cdn . 'examples/jsm/',
        ];
    }
}
